fos_user:
    db_driver: orm
    firewall_name: main
    user_class:     App\Entity\User
    registration:
        form:
            type: App\Form\Type\RegistrationType
    from_email:
        address: 'contact@boilerplate.fr'
        sender_name: boilerplate

    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager