twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # pre built theme
    #form_themes: ['bootstrap_4_layout.html.twig']
    # custom theme
    ## TO_UPDATE
    form_themes: ['form/bp_form_theme.html.twig']
